Initial fork of microsoft/omi to a PowerShell specific version

diff --git a/Unix/configure b/Unix/configure
--- a/Unix/configure
+++ b/Unix/configure
@@ -5,7 +5,7 @@
 ## configuredir
 ## rootrelative
 ## root
-##     Determine the root directory of the distribution (not necessarily the 
+##     Determine the root directory of the distribution (not necessarily the
 ##     same as the current directory, since configure can be run anywhere).
 ##
 ##==============================================================================
@@ -30,24 +30,24 @@ fullproduct="Open Management Infrastructure"
 # As a result, if version file can't be found, consider it fatal and
 # don't generate a bogus one
 
-if [ -f ../../omi.version ]; then
-    . ../../omi.version
+# JBOREAN CHANGE: Relocate the omi.version file to the root of the directory
+if [ -f ../omi.version ]; then
+    . ../omi.version
 fi
 
-if [ -n "$OMI_BUILDVERSION_MAJOR" -a -n "$OMI_BUILDVERSION_MINOR" -a -n "$OMI_BUILDVERSION_PATCH" -a -n "$OMI_BUILDVERSION_BUILDNR" ]; then
+if [ -n "$OMI_BUILDVERSION_MAJOR" -a -n "$OMI_BUILDVERSION_MINOR" -a -n "$OMI_BUILDVERSION_PATCH" ]; then
     major=$OMI_BUILDVERSION_MAJOR
     minor=$OMI_BUILDVERSION_MINOR
     revision=$OMI_BUILDVERSION_PATCH
-    patch_level=$OMI_BUILDVERSION_BUILDNR
 else
-    echo "*** UNABLE TO LOCATE FILE omi.version; USING VERSION 1.0.8.6 ***" >& 2
-    echo "*** Update build process to include omi.version from superproject! ***" >& 2
+    echo "*** UNABLE TO LOCATE FILE omi.version; USING VERSION 0.0.0.0 ***" >& 2
 
-    major=1
+    major=0
     minor=0
-    revision=8
-    patch_level=6
+    revision=0
 fi
+
+patch_level=${OMI_BUILDVERSION_BUILDNR:-0}
 
 version="$major.$minor.$revision"
 version_with_release="$major.$minor.$revision-$patch_level"
@@ -115,51 +115,51 @@ do
       ;;
 
     --prefix=*)
-      prefix=$arg 
+      prefix=$arg
       ;;
 
     --bindir=*)
-      bindir=$arg 
+      bindir=$arg
       ;;
 
     --libdir=*)
-      libdir=$arg 
+      libdir=$arg
       ;;
 
     --includedir=*)
-      includedir=$arg 
+      includedir=$arg
       ;;
 
     --datadir=*)
-      datadir=$arg 
+      datadir=$arg
       ;;
 
     --localstatedir=*)
-      localstatedir=$arg 
+      localstatedir=$arg
       ;;
 
     --sysconfdir=*)
-      sysconfdir=$arg 
+      sysconfdir=$arg
       ;;
 
     --providerdir=*)
-      providerdir=$arg 
+      providerdir=$arg
       ;;
 
     --providerdir=*)
-      providerdir=$arg 
+      providerdir=$arg
       ;;
 
     --certsdir=*)
-      certsdir=$arg 
+      certsdir=$arg
       ;;
 
     --authdir=*)
-      authdir=$arg 
+      authdir=$arg
       ;;
 
     --outputdirname=*)
-      outputdirname=$arg 
+      outputdirname=$arg
       ;;
 
     --enable-werror)
@@ -195,21 +195,21 @@ do
       ;;
 
     --openssl=*)
-      openssl=$arg 
+      openssl=$arg
       ;;
 
     --opensslcflags=*)
-      opensslcflags=$arg 
+      opensslcflags=$arg
       opensslcflags_found=1
       ;;
 
     --openssllibs=*)
-      openssllibs=$arg 
+      openssllibs=$arg
       openssllibs_found=1
       ;;
 
     --openssllibdir=*)
-      openssllibdir=$arg 
+      openssllibdir=$arg
       openssllibdir_found=1
       ;;
 
@@ -375,7 +375,7 @@ OPTIONS:
                             rather than from the install directories. This
                             also enable unit tests.
     --outputdirname         The name of the output directory where the binary
-                            files are placed. This name must not contain 
+                            files are placed. This name must not contain
                             slashes.
     --openssl=PATH          Full path to the 'openssl' command.
     --opensslcflags=FLAGS   Extra C flags needed for OpenSSL.
@@ -392,7 +392,7 @@ OPTIONS:
     --disable-localsession  Disable MI_Context_GetLocalSession function.
     --disable-indication    Disable indication feature from omiserver.
     --disable-shell         Disable shell feature from omiserver.
-    --enable-preexec        Enable execution of 'pre-exec' programs. These 
+    --enable-preexec        Enable execution of 'pre-exec' programs. These
                             programs are executed by the server (as root)
                             before invoking the associated provider for the
                             first time.
@@ -472,12 +472,12 @@ if [ "$enable_ulinux" = "1" ]; then
     openssl100_dir=/usr/local_ssl_1.0.0
     openssl110_dir=/usr/local_ssl_1.1.0
 
-    case "`uname -m`" in    
+    case "`uname -m`" in
         x86_64 )
             openssl100_libdir=${openssl100_dir}/lib64
             openssl110_libdir=${openssl110_dir}/lib
             ;;
-        
+
         * )
             openssl100_libdir=${openssl100_dir}/lib
             ;;
@@ -1254,12 +1254,12 @@ cat > $tmpdir/sem_timedwait_func.c <<EOF
 
 int main()
 {
-    sem_t sem;    
+    sem_t sem;
     if(sem_init(&sem, 0, 1) == 0)
     {
-        struct timespec temp = {0};        
+        struct timespec temp = {0};
         sem_timedwait(&sem, &temp);
-    }    
+    }
     return 0;
 }
 EOF
@@ -1697,7 +1697,7 @@ if [ "$dev" = "1" ]; then
       cp -r $rootrelative/etc/creds/* $credsdir
       sudo chmod 700 $credsdir
       test -d $credsdir && echo "created $credsdir"
-      
+
       echo "NtlmCredsFile=$credsdir/ntlm" >>$fn/omiserver.conf # register the creds file
     else
       echo "required file $fn/omiserver.conf not found"
@@ -1734,12 +1734,12 @@ fi
 chmod +w $fnnitsargs
 
 ntlm_supported=`$buildtool ntlm`
-if [ $ntlm_supported ]; then 
+if [ $ntlm_supported ]; then
    echo "NTLM auth can be supported on this platform"
 fi
 
 have_gssapi_ext=`$buildtool gssapi_ext`
-if [ $have_gssapi_ext ]; then 
+if [ $have_gssapi_ext ]; then
    echo "gssapi_ext is present on this platform"
 fi
 
@@ -2028,6 +2028,7 @@ rm -rf $fn
 echo "#define MI_MAJOR $major" >> $fn
 echo "#define MI_MINOR $minor" >> $fn
 echo "#define MI_REVISION $revision" >> $fn
+echo "#define MI_PATCH_LEVEL $patch_level" >> $fn
 
 cat $root/common/MI.h >> $fn
 
@@ -2114,7 +2115,7 @@ if [ "$dev" = "1" ]; then
   openssl x509 -outform der -in $certsdir/omi.pem -out $certsdir/omi.der
   chmod 600 $certsdir/omikey.pem
   chmod 644 $certsdir/omi.pem
-  echo "built certificates in directory: " $certsdir 
+  echo "built certificates in directory: " $certsdir
 fi
 
 ##==============================================================================
@@ -2296,23 +2297,23 @@ fi
 ## Install configuration files.
 ##
 
-if test ! -f "\$destdir/$sysconfdir/omiserver.conf" 
-then 
+if test ! -f "\$destdir/$sysconfdir/omiserver.conf"
+then
     cp $rootrelative/etc/omiserver.conf \$destdir/$sysconfdir/omiserver.conf
 fi
 
 if test ! -f "\$destdir/$sysconfdir/omicli.conf"
-then 
+then
     cp $rootrelative/etc/omicli.conf \$destdir/$sysconfdir/omicli.conf
 fi
 
 if test ! -f "\$destdir/$sysconfdir/omigen.conf"
-then 
+then
     cp $rootrelative/etc/omigen.conf \$destdir/$sysconfdir/omigen.conf
 fi
 
 if test ! -f "\$destdir/$sysconfdir/omireg.conf"
-then 
+then
     cp $rootrelative/etc/omireg.conf \$destdir/$sysconfdir/omireg.conf
 fi
 
@@ -2549,7 +2550,7 @@ rm -f $fn
 
 case $os in
         Linux)
-            if [ -f /etc/S[uU]SE-release ]; then 
+            if [ -f /etc/S[uU]SE-release ]; then
                 cp $root/scripts/installpam-sles $fn.tmp
             else
                 cp $root/scripts/installpam-rhel $fn.tmp
